modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
[[mods]]
modId="l2artifacts"
version="${file.jarVersion}" #mandatory
displayName="L2 Artifacts" #mandatory
logoFile="l2artifacts.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2artifacts]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.l2artifacts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2artifacts]]
    modId="l2library"
    mandatory=true
    versionRange="[1.3.6,)"
    ordering="AFTER"
    side="BOTH"