modLoader="javafml"
loaderVersion="[41,)"
license="LGPL v2.1"
[[mods]]
modId="l2artifacts"
version="${file.jarVersion}" #mandatory
displayName="L2 Artifacts" #mandatory
logoFile="l2artifacts.png" #optional
credits="Thanks to GenshinImpact for ideas" #optional
authors="lcy0x1 and LightLand team" #optional
description='''
Genshin Impact style artifacts that helps to boost player stats.
'''
[[dependencies.l2artifacts]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.l2artifacts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2artifacts]]
    modId="l2library"
    mandatory=true
    versionRange="[1.5.2,)"
    ordering="AFTER"
    side="BOTH"